### PR TITLE
update video_info version to 2.5 which supports Youtube API v3

### PR DESCRIPTION
**Pull request by 0mega**
Bump video_info to 2.6 to solve the issue #69.
It also introduces new functionalities described [here](https://github.com/thibaudgg/video_info/issues/103)

### CODE REVIEW

**Comment by gottfrois** [comment]
Don't we need to setup youtube api keys?

**Comment by 0mega** [comment]
We probably will, but first there are some other issues. It's not working quite well. I think there is still some work to be on video_info. I'll keep you updated.

**Comment by 0mega** [comment]
Actually it seems that we don't need the API keys, because video_info offers scrapers so it's ok to use it as is.

But this PR won't solve anything, we will have to wait for more 4 issues of video_thumbnailer to be implemented and then update the version to 2.6. The fix for the #69 is already implemented in video_info master.

Cheers

**Comment by gottfrois** [comment]
Issue fixed in `v3.1.1`

**Pull request closed without merging**
