### PR TITLE
Use frozen string literal to reduce number of string allocation

### PR DESCRIPTION
**Pull request by redtachyons**

### CODE REVIEW

**Comment by gottfrois** [comment]
Hey @redtachyons thanks for the PR. Does it really has that big of an impact?

**Comment by maia** [comment]
@gottfrois As far as I know, very much depends on if strings are frequently recreated – if they are, it drastically reduces the time spent in GC. 

It will at least have no negative side effects, unless the library attempts to alter a frozen string, which would raise an error (which would be easily identifiable).

Oh: `frozen_string_literal` is only supported by Ruby 2.3 upwards.

**Comment by redtachyons** [comment]
@gottfrois this gem was the second top gem in terms of number of allocated objects after rails. And adding `frozen_string_literal` will reduce the number of objects allocation. 

@maia Yes, only in 2.3 and above, but at least it won't break for old versions. Also frozen string errors are already handled in the PR

**Comment by redtachyons** [comment]
For some reason git made a huge diff for changing just two lines :confused:

**Comment by maia** [comment]
by the way, rubocop defaults to requiring an empty line after the last "magic comment" (such as frozen_string_literal): [Layout/EmptyLineAfterMagicComment](http://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Layout/EmptyLineAfterMagicComment)

**Comment by gottfrois** [comment]
> this gem was the second top gem in terms of number of allocated objects after rails. And adding frozen_string_literal will reduce the number of objects allocation.

@redtachyons oh realy! How did you get that information?

**Comment by maia** [comment]
@gottfrois While I'm not redtachyons, I can highly suggest [SamSaffron/memory_profiler](https://github.com/SamSaffron/memory_profiler). You can limit the analysis to a single gem, and display allocated and retained objects by their file lines.

**Comment by gottfrois** [comment]
I'm guessing most of string allocations comes from loading all those HTML pages and parsing them with nokogiri

**Comment by redtachyons** [comment]
> @redtachyons oh realy! How did you get that information?

From this tool https://github.com/schneems/derailed_benchmarks

**Comment by gottfrois** [comment]
@redtachyons can you simply address this feedback please? 

> by the way, rubocop defaults to requiring an empty line after the last "magic comment" (such as frozen_string_literal): Layout/EmptyLineAfterMagicComment

I'll be pleased so merged and cut a new release after this

**Comment by redtachyons** [comment]
Done, should I squash them into single commit ?

**Comment by gottfrois** [comment]
`v3.3.2` Thanks guys!

**Pull request merged**
